// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdsdytletfvbgcxuduqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkc2R5dGxldGZ2YmdjeHVkdXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDI2MDIsImV4cCI6MjA2NjI3ODYwMn0.UItd082Gnnf397yRmwF5fMeUnGkbGQ2Rx7hXvFCmEXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});